# permissions for end users to view uuids.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: uuid-viewer-role
rules:
- apiGroups:
  - apis.example.org
  resources:
  - uuids
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apis.example.org
  resources:
  - uuids/status
  verbs:
  - get
