# permissions for end users to edit uuids.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: uuid-editor-role
rules:
- apiGroups:
  - apis.example.org
  resources:
  - uuids
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apis.example.org
  resources:
  - uuids/status
  verbs:
  - get
